---
- name: Delete admin ssh keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: absent
    key: "{{lookup('file', item )}}"
  with_fileglob:
    - "../../../secrets/ssh_keys/admins/deny/*.pub"
