---
- name: Install aptitude to use for full upgrades
  become: true
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - aptitude
    - deborphan
  tags: setup_apt

- name: run "aptitude upgrade"
  become: true
  apt: upgrade=yes
  tags: setup_apt

- name: run "apt-get autoremove"
  become: true
  apt: autoremove=yes
  tags: setup_apt
